### ISSUE TITLE
Locked out 

### ISSUE THREAD

**Issue by Jessica4949** [tombriden/passwdsafe#1]
I’ve had the is app for years now and I’ve had the same password since the begining. I was saving a new password in the app Andy when I went to click save the app shut down. When I tried to get back into the app it kept saying the password I was using was wrong. I’ve never changed the password. Now I can’t get into the app and I NEED those passwords. If you could advise me on how to either fix the problem or atleast get these passwords off the app that would be very much appreciated. Thank you.

**Comment by tombriden** [comment]
Hi, do you have a backup of the password file from before you tried to change the password? 
If not, you'd be better off asking for help on the official project site here https://sourceforge.net/p/passwdsafe/discussion/

**Comment by Jessica4949** [comment]
I never changed the password, its just telling me I have the wrong password every time I try and get in. Iv never changed the password. Would it back up with everything else on my phone when my phone backs up? or would I have had to back it up manually?  

    On Monday, October 23, 2017 3:47 AM, Tom Briden <notifications@github.com> wrote:
 

 Hi, do you have a backup of the password file from before you tried to change the password?
If not, you'd be better off asking for help on the official project site here https://sourceforge.net/p/passwdsafe/discussion/—

**Comment by tombriden** [comment]
Ah ok, I misread that as the app crashing while you were changing the password. If it crashed during a save it's possible the file got corrupted so you may need to try and find an older copy of the file or a backup. Again, you'll be better off posting in the official site forum on sourceforge. I'm not the author of the application, this repo is just a copy of the code, so I'm not the best person to ask for help
